name: Publish Package to npmjs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1

      - name: Set node version to 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run build:v2
      - run: pnpm run build:v3
      - run: pnpm run build:style

      - run: pnpm publish --access=public --filter=@charrue/layout
      - run: pnpm publish --access=public --filter=@charrue/layout-next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}